//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class activity
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public activity()
    {
        this.comments = new HashSet<comments>();
        this.like = new HashSet<like>();
    }

    public int id { get; set; }
    public string type { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public Nullable<int> activity_by { get; set; }
    public string activity_include { get; set; }
    public Nullable<int> TotalLike { get; set; }
    public Nullable<int> TotalDislike { get; set; }
    public string title { get; set; }
    public Nullable<int> score { get; set; }

    public virtual user user { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<comments> comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<like> like { get; set; }
}

public partial class comments
{
    public int id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> activity_id { get; set; }
    public string comment_text { get; set; }

    public virtual activity activity { get; set; }
    public virtual user user { get; set; }
}

public partial class like
{
    public int id { get; set; }
    public Nullable<int> activity_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> total { get; set; }
    public Nullable<int> min { get; set; }

    public virtual activity activity { get; set; }
    public virtual user user { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class user
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {
        this.activity = new HashSet<activity>();
        this.comments = new HashSet<comments>();
        this.like = new HashSet<like>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string surname { get; set; }
    public string username { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> birthdate { get; set; }
    public string department { get; set; }
    public string password { get; set; }
    public string photo { get; set; }
    public Nullable<int> rol { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<activity> activity { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<comments> comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<like> like { get; set; }
}
